version: '3.9'

services:
  app1:
    # Берем Dockerfile из каталога app
    # build: ./app1
    build:
      context: ./app
    # Запускаем тестовый сервер
    command: python3 manage.py runserver 0.0.0.0:8000
    # куда будут помещены данные из каталога app
    volumes:
      - ./app/:/usr/src/app/
    # Открываем порт 8000 внутри и снаружи
    ports:
      - "8000:8000"
    # Файл содержащий переменные для контейнера
    # env_file:
    #   - ./.env1.dev
